### ISSUE TITLE
Connect admin role user doesn't have privilege to admin functionalities.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/forums#114]
Description:
Connect Admin role user (TCConAdmin) doesn't have privilege for admin functions.

1. Not able to attach files
2. Not able to edit/Delete other users post.

![image](https://user-images.githubusercontent.com/55895538/98226483-70ed7680-1f99-11eb-9eb0-5521ebb04e17.png)

**Comment by sandhiyakavi** [comment]
Userhandle used TCConAdmin

**Comment by drasticdpk** [comment]
Verified it is working as expected and closing it. cc @sdgun 
Reference :
![image](https://user-images.githubusercontent.com/25297859/98780346-ba681680-241c-11eb-8f0c-737bd582afa1.png)
![image](https://user-images.githubusercontent.com/25297859/98780576-17fc6300-241d-11eb-9fc1-e4f6674eecbf.png)
