### ISSUE TITLE
Able to upload all types of files using the image upload icon.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/forums#116]
Description:
Able to upload all types of files using the image upload icon.

![image](https://user-images.githubusercontent.com/55895538/98231019-38509b80-1f9f-11eb-9442-c0fb2e0fb07c.png)
[image_upload.zip](https://github.com/topcoder-platform/forums/files/5493736/image_upload.zip)

**Comment by jmgasper** [comment]
I don't think this is a bug.
