### ISSUE TITLE
The forum link in the challenge page should open the forum in a separate tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#119]
**Steps**
Go to a challenge details page ex- https://qa-community-app.topcoder-dev.com/challenges/99ac6731-0c23-42a4-9193-abbde35b8394
Click CHALLENGE DISCUSSION link

**Actual result**
The forum is opened in the same tab

**Expected result**
The forum should be opened in a separate tab

**Comment by jmgasper** [comment]
@sdgun - Moved this into the community app:  https://github.com/topcoder-platform/community-app/issues/5169
