### ISSUE TITLE
Rename the link from forum to challenge as ''Back to Challenge Details page"

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#120]
**Steps**
Go to a challenge overview - ex-https://vanilla.topcoder-dev.com/discussion/1514/challenge-overview/p1
See the link back to challenge page

**Expected result**
Rename to ''Back to Challenge Details page"

![image](https://user-images.githubusercontent.com/4592712/98322031-7fc14100-200c-11eb-9f4f-379dc6c2215b.png)

**Comment by jmgasper** [comment]
Done, for newly created challenges:
![Screen Shot 2020-11-06 at 17 52 49](https://user-images.githubusercontent.com/21790/98335384-f2f0a480-2058-11eb-9503-c33ba6b72fe0.png)

**Comment by sdgun** [comment]
Verified in a new challenge forum, the link is renamed as expected.

**Comment by sdgun** [comment]
This issue can be seen again in the newly created challenge forums

https://vanilla.topcoder-dev.com/discussion/1665/challenge-overview#latest
https://vanilla.topcoder-dev.com/discussion/1655/challenge-overview#latest

![image](https://user-images.githubusercontent.com/4592712/98632073-bbc61000-2344-11eb-9c39-69aa50d5c871.png)

**Comment by jmgasper** [comment]
@sdgun - Redeploying now.  The change was originally only made for development challenges.  I have now applied it to QA, Design, and Data Science.

**Comment by sdgun** [comment]
To be verified after fixing - https://github.com/topcoder-platform/forums/issues/160

**Comment by sdgun** [comment]
This issue is fixed.
