### ISSUE TITLE
Discussion summary only allows 100 characters, the existing forum threads exist with more than 100 characters

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#122]
**Steps**
Go to the forum home page from a normal user(ex user- TopConnCustomer link - https://vanilla.topcoder-dev.com/)
Click New Discussion button
Enter more than 100 characters in the discussion title

**Actual result**
Only allows 100 characters

The existing forums allow more than 100 characters and there are already thread titles with > 100 characters(ex-https://apps.topcoder.com/forums/?module=Thread&threadID=847307&start=0)

**Comment by jmgasper** [comment]
@rootelement - Do you think this one needs to be fixed?  This may require Vanilla source code changes.

**Comment by rootelement** [comment]
No. This is a fine limitation. There's no need for a title that long.
