### ISSUE TITLE
User can post comments without adding any messages

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#147]
**Steps**
Go to the forum https://vanilla.topcoder-dev.com
On any thread add a comment without any text

**Actual result**
Allowed

![image](https://user-images.githubusercontent.com/4592712/98627118-70f2cb00-2339-11eb-896d-fa5b7e880e67.png)

**Comment by jmgasper** [comment]
Updated the minimum comment length to 1

**Comment by sdgun** [comment]
Verified.
