### ISSUE TITLE
Challenge overview has two links to the challenge details page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#148]
**Steps**
Go to a challenge overview - ex-https://vanilla.topcoder-dev.com/discussion/1655/challenge-overview#latest
Click the two links 

Both navigate back to the challenge page, the first link previously used to navigate back to the forum 

![image](https://user-images.githubusercontent.com/4592712/98633213-fcbf2400-2346-11eb-997a-ec996d94b5c4.png)

**Comment by jmgasper** [comment]
Yeah, this change was requested by Topcoder.  The second link should be `Back to Challenge Details page`, and the first will show in threads underneath the challenge group.
