### ISSUE TITLE
Inserting an invalid url in the post shows the red error ribbon in the editor

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#153]
**Steps**
Log into forums as any user ex- https://vanilla.topcoder-dev.com/
Access any forum available to the user
Go to add comment
Click 'Embed'
Enter an invalid url 
Click insert

Shows the red error ribbon in the editor

[Reply - invalid url.zip](https://github.com/topcoder-platform/forums/files/5515492/Reply.-.invalid.url.zip)

**Comment by jmgasper** [comment]
I think this is fine.  We'll table it for now.
