### ISSUE TITLE
txt file attachments cannot be downloaded or opened

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#155]
**Steps**
Log into forums as any user https://vanilla.topcoder-dev.com/discussion/1639/welcome?view=threaded
Click on the txt file attachment in the comments

File is not opened or not downloaded, it opens up a separate web page

[Screencast 2020-11-10.zip](https://github.com/topcoder-platform/forums/files/5515650/Screencast.2020-11-10.zip)

**Comment by atelomycterus** [comment]
@jmgasper Duplicate issue -https://github.com/topcoder-platform/forums/issues/104.
