### ISSUE TITLE
The challenge forums are not created for the newly created challenges

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#160]
**Steps**
Created a few new challenges
https://www.topcoder-dev.com/challenges/88485971-c6e1-4203-9246-6858f6b3870c
https://qa-community-app.topcoder-dev.com/challenges/981d8564-7ceb-4de5-990d-e8ff1495abcf
https://qa-community-app.topcoder-dev.com/challenges/aa6f477b-599c-464a-b7d2-d959826c6474

Search for those challenges in the forums but they are not available(we cannot open the challenge forum from challenge details page since it is giving 502 error)

We now don't have a way to access new challenge forums we create due to this issue

**Comment by jmgasper** [comment]
Ok - for the ones above, the processor didn't add the URL properly.  We had issues with that for a short time, but it is working again.  I just validated it with `de578523-bede-4cce-8434-350a8c6e392c`

**Comment by jmgasper** [comment]
https://qa-community-app.topcoder-dev.com/challenges/de578523-bede-4cce-8434-350a8c6e392c

**Comment by sdgun** [comment]
@jmgasper created the below challenges today, but none of them are available in vanilla forum when search by the name, in the challenge details page we see the link CHALLENGE FORUM which leads to 502 error.

https://qa-community-app.topcoder-dev.com/challenges/381a079f-a4cd-4f97-941a-bf25720a313d
https://qa-community-app.topcoder-dev.com/challenges/4ef64187-aae1-4f93-9ec2-805f09e82dbe
https://qa-community-app.topcoder-dev.com/challenges/d573a6ff-506a-4729-93d3-76d01588a97b

The forum object is missing the url in above challenges

But for the below challenge which was created around the same time as above has the vanilla forum url
https://qa-community-app.topcoder-dev.com/challenges/79660ffd-8b8c-42e3-9ade-8fb2aa669e37
