### ISSUE TITLE
Discussion created is displaying under both General as well as challenge Forum.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/forums#161]
Description:
New Discussion created under General topic using the New discussion button in a challenge Forum is displayed in both General as well as under the challenge forum.

Steps to Reproduce:

1. Open a challenge Forum.(https://vanilla.topcoder-dev.com/group/159)
2. Click New discussion button.
3. Choose the General TopCoder Cookbook Discussion under Topcoder CookBook general topic.
4. Create a new discussion.

Actual result:
The created discussion is getting displayed under both Topcoder CookBook as well as Challene Forum.

Expected result:
The created discussion should be displayed under Topcoder CookBook or user should not be allowed to select other Forums under a particular forum.

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/98775849-42f0b200-2431-11eb-9ad3-ca575d6b4e35.png)

![image](https://user-images.githubusercontent.com/55895538/98775510-9f9f9d00-2430-11eb-8087-102c3d75d485.png)

Video:
[create_discussion.zip](https://github.com/topcoder-platform/forums/files/5522173/create_discussion.zip)

**Comment by jmgasper** [comment]
I think this has been fixed.

**Comment by sdgun** [comment]
Verified, this is fixed.
