### ISSUE TITLE
Challenge forum categories are not displayed for some registered normal user

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#164]
**Steps**
Log in as normal user sdgunvfor and go to https://qa-community-app.topcoder-dev.com/challenges/69cb5726-8bcc-4b56-b45a-a9b85e91e4ed
Click on the CHALLENGE DISCUSSION link

No categories shown to this registered user, but when log in as normal user sdguntcqa and copilot user TCConnCopilot, the categories are available in the forum

[Screencast 2020-11-11.zip](https://github.com/topcoder-platform/forums/files/5522558/Screencast.2020-11-11.zip)

**Comment by atelomycterus** [comment]
@jmgasper Duplicate issue - #211
