### ISSUE TITLE
Unable to post comment by Admin

### ISSUE THREAD

**Issue by drasticdpk** [topcoder-platform/forums#166]
**Steps** 
1. Go to given URL https://vanilla.topcoder-dev.com/discussion/1680/b1 
2. Try to post comment.

**User** : TCConAdmin 

**Reference** 
![image](https://user-images.githubusercontent.com/25297859/98783180-3fedc580-2421-11eb-96b5-8c10d56d74bd.png)

**Comment by jmgasper** [comment]
Permission issue - should be fixed now
