### ISSUE TITLE
Email notification doesn't have much information

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/forums#180]
Description:

The Email notification sent to the members doesn't contain below information
1. It doesn't contain the challenge name to which the thread belongs.
2. The post is not getting displayed in the mail. The user has to login to vanilla Forum to view the post.
3. The recipient username is not addressed in the mail.

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/98923617-39da1080-2517-11eb-939f-c600617de596.png)

Current Forum mail notification:
<img width="614" alt="mail_format" src="https://user-images.githubusercontent.com/55895538/98923643-42cae200-2517-11eb-898b-ea98ca615373.png">

**Comment by jmgasper** [comment]
Duplicates (more or less):  https://github.com/topcoder-platform/forums/issues/70
