### ISSUE TITLE
The Challenge Discussion tab with irrelevant discussions are displayed for the Unregistered user.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/forums#193]
Description:

The challenge Discussion tab is available for the unregistered user who is also not a member of the challenge. Also on clicking the Challenge discussion tab, the discussions displayed under the challenge forum belongs to various other Challenges.

Note: Correct discussions are displayed once user registers to the challenge.

 unregistered user : TopConnCustomer
Challenge link:  https://qa-community-app.topcoder-dev.com/challenges/c568d386-05c7-4885-a60a-975f8821c8f7

Screenshot:

![image](https://user-images.githubusercontent.com/55895538/99215160-7e1a2900-2815-11eb-9b9a-c96a0f8975d1.png)
![image](https://user-images.githubusercontent.com/55895538/99215560-a22a3a00-2816-11eb-95ad-36b1899e6742.png)

In Vanilla forum:
![image](https://user-images.githubusercontent.com/55895538/99215190-8ffbcc00-2815-11eb-84af-ecabe256c724.png)

On clicking a discussion:
![image](https://user-images.githubusercontent.com/55895538/99215289-cf2a1d00-2815-11eb-8b77-0513f4912003.png)
![image](https://user-images.githubusercontent.com/55895538/99215364-01d41580-2816-11eb-8286-01201083fec2.png)

**Comment by jmgasper** [comment]
I think this has been cleaned up, at least on the forums side.
