### ISSUE TITLE
Watch/Follow is not set by default for the members of the Challenge 

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/forums#195]
Description:

Watch and Follow forum is not set by default for the members of the challenge (Manager/Admin)

Admin - Both Code Documents and Code Questions are not in Watch/Follow status.
Manager - Code Documents are in Watching/Following status and Code Questions are not in Watch/Follow status.

screenshot:

Admin
![image](https://user-images.githubusercontent.com/55895538/99225526-89784f00-282b-11eb-9728-25f54863449c.png)
![image](https://user-images.githubusercontent.com/55895538/99225579-9e54e280-282b-11eb-93bb-6f35798cf74c.png)

Manager:
![image](https://user-images.githubusercontent.com/55895538/99225626-b4fb3980-282b-11eb-893f-a8e0f045e436.png)
![image](https://user-images.githubusercontent.com/55895538/99225659-c0e6fb80-282b-11eb-9378-7808989a0b3f.png)

**Comment by jmgasper** [comment]
We don't want to watch / follow by default for admin / observers.  We'll only do this for copilots and members.
