### ISSUE TITLE
For the copilot/admin users and normal user who registers to a challenge, all the discussions in that challenge forum are listed in Recent Discussions page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#198]
**Steps**
Register to a challenge as a normal user(sdgunvfor) (challenge registered - https://qa-community-app.topcoder-dev.com/challenges/af9a78f4-806c-4ec9-94b6-72a2db2d3d76)
Go to the forums
Click Recent Discussions

For the registered user all the discussions in that challenge forum are listed in Recent Discussions page
For copilot and admin also these newly created challenge's all discussions are listed in Recent Discussions page

Do we want to list them by default in this section? Shouldn't recent discussions only list the discussions which were created/commented/replied by the user?

![image](https://user-images.githubusercontent.com/4592712/99356823-d95d2180-28d0-11eb-903f-b6547434beb0.png)

**Comment by jmgasper** [comment]
@sdgun - I *think* what we have now is fine.  Do you think this will be confusing to the user?

**Comment by sdgun** [comment]
@jmgasper I felt so, just raised the question in the forum to get the feedback from Oanh

**Comment by atelomycterus** [comment]
@jmgasper @sdgun Vanilla algorithm in Recent Discussions page:
Our Vanilla configuration uses 'following a category' feature.  

Recent Discussion '/discussions'":  

1. Check  user preferences.  User can view all categories or following
2.a. if view='All':
Get a list of categories that a user has permission to view.
2.b if View='Following'
Get a list of categories followed  by user 

3. Search Announcement by categoryIds + Search Discussions by categoryIds

4.  Show a list of Announcements + Show a list of Discussions

@sdgun' s screen. User registered => User is following all challenge's categories, 2 announcements are shown , then discussions
![image](https://user-images.githubusercontent.com/10196632/99367522-20481880-28cb-11eb-8a08-59d81808100d.png)

Recent discussions view may differ from user to user (depending on `following categories'  +
sorting chronological by most recent comment+ other sorting keys)

We can change it to meet our requirements.

**Comment by atelomycterus** [comment]
@jmgasper I have already found a solution not to show group posts in recent discussions. The Category settings has 'Hide from the recent discussions page.':
![image](https://user-images.githubusercontent.com/10196632/99387639-67db9e00-28e5-11eb-9435-3db2c2e1e55f.png)

I created the category Demo with the nested category 'News'. The same settings is used for group categories created by a challenge processor.   I enabled 'Hide from the recent discussions page' for both categories. It is disabled by default.  Created 3 post with 3 diff options in the News:
![image](https://user-images.githubusercontent.com/10196632/99388410-97d77100-28e6-11eb-8945-932ac4af429b.png)


1. Recent discussions page (/discussions) - is a default page, displays all discussion by all categories. Checked next pages, 2 discussions weren't displayed.  All posts created by challenge processor are saved with the option 'in the category'. 
![image](https://user-images.githubusercontent.com/10196632/99387986-efc1a800-28e5-11eb-8a79-fbf09e8486c1.png)

2. The category Demo
![image](https://user-images.githubusercontent.com/10196632/99388319-72e2fe00-28e6-11eb-8b51-5f8d41acfbaf.png)

3. Recent discussions page when the category News  selected:
![image](https://user-images.githubusercontent.com/10196632/99388283-6494e200-28e6-11eb-9347-199cbf99fff8.png)


### What should be implemented to hide  group posts from recent discussions
-  I've checked Vanilla source code. 'Hide from the recent discussions page' is available from UI. So need to add this param in Vanilla Rest API.
-  update a challenge processor 
- in dev/prod for existing data: set 'HideAllDiscussions' = 1 for existing group categories in DB.  It can be implemented with Vanilla API during deploying.

**Comment by jmgasper** [comment]
@atelomycterus - Ok, thanks for that.  I'll let you know what we decide.

**Comment by sdgun** [comment]
@atelomycterus do you know the behavior of 'Sink'?

![image](https://user-images.githubusercontent.com/4592712/99497731-543f3e80-299c-11eb-8186-b01e165a2e8f.png)

**Comment by atelomycterus** [comment]
@sdgun @jmgasper - Sunk discussions do not move to the top of the discussion list when a new comment is added.
Let me know if you have any questions.

**Comment by sdgun** [comment]
@jmgasper Oanh has confirmed this behavior is ok in the forum slack group, can I close this?

**Comment by jmgasper** [comment]
@sdgun - Sure, go ahead, thanks
