### ISSUE TITLE
Link to Gig work in the forum notification email needs to be corrected

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#200]
**Steps**
Go to a notification received to an email
Click the link Gig work

It's opening https://www.topcoder.com/community/taas

![image](https://user-images.githubusercontent.com/4592712/99361841-ba628d80-28d8-11eb-99aa-3804e588c82d.png)

![image](https://user-images.githubusercontent.com/4592712/99361919-d23a1180-28d8-11eb-9469-e694afbadbe3.png)

**Comment by jmgasper** [comment]
Fix deploying now.  Give it 10 minutes for a retest.

**Comment by sdgun** [comment]
Verified, it's redirecting to https://www.topcoder-dev.com/gigs
