### ISSUE TITLE
Copilot doesn't have an option to upload attachments in the new editor

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#206]
**Steps**
Log in to forums as a copilot user (TCConnCopilot)
Go to any available challenge forum discussion 
Click New Discussion
Check the editor

The editor doesn't have an option to upload an attachment for the copilot

![image](https://user-images.githubusercontent.com/4592712/99626044-6500ba80-2a57-11eb-8b80-0be309ae1048.png)

**Comment by jmgasper** [comment]
@sdgun - Drag and drop works.  I think that's fine for now.

![Screen Shot 2020-11-19 at 17 04 57](https://user-images.githubusercontent.com/21790/99627957-5af7af80-2a89-11eb-9d85-d8f9387badb3.png)

**Comment by sdgun** [comment]
@jmgasper For admin drag & drop works but for copilot it doesn't work. For admin there is also a Browse button which is missing for copilot user.

[Attachments.zip](https://github.com/topcoder-platform/forums/files/5564762/Attachments.zip)

Admin:
![image](https://user-images.githubusercontent.com/4592712/99629370-e6f3e200-2a5d-11eb-8e72-f7f5b47e7caa.png)

**Comment by jmgasper** [comment]
@sdgun - Ok, I tweaked some permissions.  SHould be fixed now, thanks.

**Comment by sdgun** [comment]
Thanks, it is available for the copilot now
