### ISSUE TITLE
Topcoder logo is a broken image in the notification email

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#210]
**Steps**
Verify an email notification received on a forum discussion/comment

Topcoder logo is a broken image in the notification email

![image](https://user-images.githubusercontent.com/4592712/99651032-1f0a1d80-2a7c-11eb-8565-f0642c937b13.png)

**Comment by jmgasper** [comment]
Fixed

**Comment by sdgun** [comment]
Verified this issue is fixed now.

![image](https://user-images.githubusercontent.com/4592712/99756857-1107db80-2b14-11eb-963d-c4830df70dff.png)
