### ISSUE TITLE
Unable to create new discussions/comments/reply to existing comments

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#225]
**Steps**
Log in as  TCConnCopilot to https://vanilla.topcoder-dev.com/post/discussion/bf6d0efd-b4f8-4846-a7df-82227d4248ff-documents
Create a new discussion/comments/reply 

Get the below error
![image](https://user-images.githubusercontent.com/4592712/99929430-39414580-2d73-11eb-861c-181abbe3191c.png)

The editor is not the MD editor

**Comment by atelomycterus** [comment]
@sdgun The issue with parsing data in Vanilla. The post format has been changed.
@jmgasper The prev post format was rich. Now RichEditor pligun is disabled in the dev. The post format is 'Text'.
Let me know which editor will be used and which format will be by default.
![image](https://user-images.githubusercontent.com/10196632/99934312-b8804a80-2d6e-11eb-9a33-2989fcd987c0.png)

**Comment by jmgasper** [comment]
@atelomycterus - We're going to use the Advanced Editor.  For some reason, after the deploy I have to flip the `Rich Editor` on and then off before the proper editor shows up.

@sdgun - Should be fixed for now.

**Comment by sdgun** [comment]
@jmgasper Thanks, it is fixed now
