### ISSUE TITLE
Observers should not automatically be subscribed to forums

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/forums#230]
Example - for this contest - https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30153349 I am an observer.

However, it appears that I am subscribed to the forum - I am receiving email notifications.

Previously, Observers would not be subscribed.

**Comment by jmgasper** [comment]
@callmekatootie - Caught and fixed already:  https://github.com/topcoder-platform/forums/issues/229
