### ISSUE TITLE
Attachments in the notification are prompted to download in a new empty tab

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#246]
**Steps**
Log in as any user and go to any discussion
Add a comment/reply or a new discussion with some word, excel file attachments
Check the email notification by logging in from another user who is watching the discussion
Click on the attachment links

Attachments in the notification are prompted to download in a new empty tab

![image](https://user-images.githubusercontent.com/4592712/100565550-ea069200-32e9-11eb-883a-52d812d408fd.png)

**Comment by jmgasper** [comment]
I think this is fine.  This is also likely a side effect of how Gmail handles things.
