### ISSUE TITLE
Cannot attach json file

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/forums#255]
The file explorer does not show json files.

Attaching json files gives the message - File format not supported.

the UI element that I am using to attach files:

![image](https://user-images.githubusercontent.com/2317133/100968517-7a95da00-3557-11eb-8272-cddf27cb8d86.png)

**Comment by callmekatootie** [comment]
Cannot attach adobe xd design file

**Comment by jmgasper** [comment]
Fixed now, both with the upload button and drag-and-drop
