### ISSUE TITLE
[Android] Bookmark icon and ellipsis are overlapping with the discussion name

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#287]
**Steps**
1. Open forums from an Android phone
2. Go to Recent Discussions (or any section)
3. Check the available discussions

Bookmark icon and ellipsis are overlapping with the discussion name

![image](https://user-images.githubusercontent.com/4592712/101861636-83f5f680-3b96-11eb-9f7a-a8f5aa406aae.png)

Device: Pixel XL
OS: Android 10
Browser: Chrome

**Comment by jmgasper** [comment]
@sdgun - What device, OS, and browser?

**Comment by sdgun** [comment]
@jmgasper Sorry, updated the description with the details
