### ISSUE TITLE
Fix OAuth Implementation

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/forums#3]
1. Get it working 100% in Dev, against Dev OAuth
1. Shut off anything other than Topcoder OAuth login

**Comment by jmgasper** [comment]
Done.  For future reference, in Plugins / OAuth2 SSO
<img width="1355" alt="Screen_Shot_2020-03-06_at_08_44_38" src="https://user-images.githubusercontent.com/21790/76028472-cc88df80-5f86-11ea-8080-967949597bb3.png">
:
