### ISSUE TITLE
New editor issue

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/forums#312]
I am facing an issue with the new editor when I try to quote the user. See gif below:

Here, I am trying to quote the user. I have copied the text and I type ">" which brings the quote format but when I paste the text, it does not work.

![new_editor](https://user-images.githubusercontent.com/2317133/102984797-29fd1580-4534-11eb-8fbd-507fc51acff4.gif)

I then try to prefix the previous text with ">" and that also won't work...

**Comment by atelomycterus** [comment]
@callmekatootie @jmgasper 

Use 'Quotes' :
![image](https://user-images.githubusercontent.com/10196632/103036056-d9101000-4579-11eb-8978-a890d419a8d6.png)


See my video:
https://user-images.githubusercontent.com/10196632/103035988-abc36200-4579-11eb-9043-4b833111e37f.mp4

**Comment by callmekatootie** [comment]
https://user-images.githubusercontent.com/2317133/103062764-4309d300-45d5-11eb-99c0-11b343f1b29d.mp4

Managed to do it in the second attempt... But the first time it fails...
