### ISSUE TITLE
Normal users can upload files in production

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#358]
**Steps**
Created a new challenge in production - Forum: https://discussions.topcoder.com/categories/ac34bef7-a634-4d2f-b5e4-c83f68d908a5
Log in as a normal user('CustomerUser') by registering to the challenge
Go to create a new comment/discussion

The upload button is available to the user and this user can upload files

Even after unregistering from the challenge this user can see the forum. I am not sure if this user is also in another higher role like copilot, but he is not in connect or OR. And I was told this user is in the normal user role in production.

**Comment by jmgasper** [comment]
@sdgun - Looks like the permission was changed.  Can you try again please?

**Comment by sdgun** [comment]
@jmgasper I checked this again, but I can still see this user can access forums even without registering to the challenges.

**Comment by sdgun** [comment]
@jmgasper Now I cannot see the upload option even for copilot users in production. I am trying from my account on the same discussion I used before

**Comment by jmgasper** [comment]
@sdgun - I fixed the upload permissions for copilots.

**Comment by sdgun** [comment]
@jmgasper Verified, Copilots can upload files now.

**Comment by sdgun** [comment]
@jmgasper I checked the 'CustomerUser' in production and this user does not see the challenge discussion link on the challenge details page but he can access the discussion groups.

**Comment by sdgun** [comment]
This issue was fixed in https://github.com/topcoder-platform/forums/issues/363
