### ISSUE TITLE
Category selection is slow in Android and the app crashes while selecting categories

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#371]
**Steps**
Go to forums from Android
Click New Discussion
Select a category and change it(keep selecting)

Category selection is very slow in Android and the app crashes while selecting categories

Device: Pixel XL
OS: Android 10
Browser: Chrome

[crash logs.txt](https://github.com/topcoder-platform/forums/files/5923823/crash.logs.txt)

[Pixel XL_Recording_20210204_1.zip](https://github.com/topcoder-platform/forums/files/5923858/Pixel.XL_Recording_20210204_1.zip)

**Comment by jmgasper** [comment]
@sdgun - What app crashes?  Chrome?

**Comment by sdgun** [comment]
@jmgasper Yes

**Comment by jmgasper** [comment]
@sdgun - Can we retest this please?

**Comment by sdgun** [comment]
@jmgasper Category selection is only available now on saved New discussions, however I couldn't reproduce this issue. Therefore closing it.
