### ISSUE TITLE
The copilot users can upload the files on roundtable discussions by switching from challenge forums to roundtables  

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#383]
**Steps**
Log into forums as copilot user
Click New Discussion
Select a challenge forum category from category drop down
Upload files
Now select a roundtable category from the category drop down
Post the discussion

The discussion is posted with the uploaded files.

https://user-images.githubusercontent.com/4592712/107400877-437c1000-6b28-11eb-9680-005a3d1374f6.mp4

**Comment by atelomycterus** [comment]
@sdgun yes, I wrote about it (https://github.com/topcoder-platform/forums/issues/373#issuecomment-774732377). 
To prevent the user from doing this, it would be correct to upload to the Filestack only after clicking 'Post Discussion'. This has its pros and cons.

**Comment by jmgasper** [comment]
@sdgun - I think this one can be retested.

**Comment by sdgun** [comment]
@jmgasper @atelomycterus They can still do this since we show the New discussions button on the bookmarks page.


https://user-images.githubusercontent.com/4592712/109752347-44bfca80-7c06-11eb-88f2-817815ae8c12.mp4

**Comment by atelomycterus** [comment]
@jmgasper 
1) Regarding the latest changes (https://github.com/topcoder-platform/forums/issues/439), `New discussion` should be removed from Bookmarks page. `New Discussion` button  has been removed from Discussions\Categories pages, the button is only available inside categories.  Please confirm it. I'll fix it on `Bookmarks` page. 
2) I've checked `My Drafts` page.  User can change a category for Draft Discussion.  Regarding the latest changes(https://github.com/topcoder-platform/forums/issues/439), the category is always defined. So  the category should be disabled/read-only  for Draft Discussion. Please confirm it. I'll fix it. 
![image](https://user-images.githubusercontent.com/10196632/109792736-e2c28d80-7c24-11eb-8d57-6b91a5137c67.png)

@sdgun Do you have any issues (e.g. 403 error, don't have permission to upload files) with uploading?

**Comment by sdgun** [comment]
@atelomycterus No I didn't observe that error in Production or Dev with for myself or the test users.

**Comment by atelomycterus** [comment]
@sdgun Thanks for info! I am trying to reproduce #452 in DEV/PROD. It works as expected, no issues.

**Comment by sdgun** [comment]
This issue is fixed after moving the New Discussion button since we don't show the category drop down to the user.
