### ISSUE TITLE
UI issue in the Move discussion pop up

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#387]
**Issue**
Log in as copilot to forums from Firefox and go to a group discussion
Click on ellipsis >> select Move

The pop up has an alignment issue

![image](https://user-images.githubusercontent.com/4592712/107635399-172fd300-6c91-11eb-95d3-47bab6d3da24.png)

This issue is also present in Android/IOS

**Comment by atelomycterus** [comment]
@sdgun Please clear browser cache. The same issue is mentioned in #117 #384. Let me know if it still exists.
Mobile:
![image](https://user-images.githubusercontent.com/10196632/107652181-5c540500-6c91-11eb-95b1-d8c9dd669af9.png)

Desktop:
![image](https://user-images.githubusercontent.com/10196632/107652242-6c6be480-6c91-11eb-8650-db4b471f8a82.png)

Firefox: 
![image](https://user-images.githubusercontent.com/10196632/107652117-4d6d5280-6c91-11eb-9fc9-0d7071ec7782.png)

**Comment by sdgun** [comment]
@atelomycterus Works fine after clearing cache, closing the issue.

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/108681177-d0ee3580-7514-11eb-80c5-829725bce80e.png)
