### ISSUE TITLE
Challenge discussions are not available for the admin user

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#401]
**Steps**
Log in as TCConAdmin
Click Challenge discussions from the left nav 

Only one discussion is available

![image](https://user-images.githubusercontent.com/4592712/107908315-c0b9e180-6f7b-11eb-8300-960ff0dbde79.png)

**Comment by atelomycterus** [comment]
@sdgun Please clear browser cache:. The Challenge Discussions look like:
![image](https://user-images.githubusercontent.com/10196632/107916743-dcbb8400-6f77-11eb-89be-6a6982e7bd61.png)

@jmgasper The page shows all challenges for which the user has registered. TCConAdmin is not a member of any challenge groups. After applying design tweaks, we removed `Available challenges` https://github.com/topcoder-platform/forums/issues/377#issuecomment-777801505.

Should  `Available challenges`  be displayed for  Admin roles? 

 TCConAdmin can go to a challenge page from discussions:
![image](https://user-images.githubusercontent.com/10196632/107917905-c1517880-6f79-11eb-9ea1-72e0899dd34a.png)

**Comment by jmgasper** [comment]
@atelomycterus - Is the admin user still able to navigate directly to the forums for all challenges?  If they can get to it by just putting in the URL, that's gonna be fine, since the admin tools used by TC link to the forums directly.

**Comment by atelomycterus** [comment]
@jmgasper yes, the admin user can navigate directly to  the forums for all challenges:
The  `Challenges Forum` category with custom permissions for 'Connect Admin' in DEV:
![image](https://user-images.githubusercontent.com/10196632/107932312-768e2b80-6f8e-11eb-8266-a785eb2ed79c.png)

**Comment by jmgasper** [comment]
@atelomycterus / @sdgun - Ok, I think that's fine then, thanks.  Admins will navigate directly to specific forums through the admin app, challenge manager, or challenge listing.   They shouldn't need to go through the challenges listing in the forums

**Comment by sdgun** [comment]
Closing as per the above discussion.

**Comment by lakshmiathreya** [comment]
<img width="1680" alt="Screenshot 2021-02-24 at 7 10 28 PM" src="https://user-images.githubusercontent.com/51733042/109009026-068d4d00-76d4-11eb-9c71-557a7cd6d147.png">

**Comment by jmgasper** [comment]
@lakshmiathreya - You're an admin - roles are sync'd from Topcoder to Vanilla when you log in.  I'm not sure what the screenshot you posted is supposed to point us to or represent, thanks.

<img width="367" alt="Screen Shot 2021-02-25 at 8 05 51 am" src="https://user-images.githubusercontent.com/21790/109065834-4853dd00-7740-11eb-9ff3-43fbfaa19fd6.png">
