### ISSUE TITLE
Discussions count is incorrect in roundtables

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#402]
**Steps**
Go to https://vanilla.topcoder-dev.com/categories
The discussions count in General is 84

But when count the discussions inside it, it is 58

![image](https://user-images.githubusercontent.com/4592712/108022646-f7106300-7046-11eb-81a1-95b45ee61472.png)

**Comment by atelomycterus** [comment]
@sdgun the same issue https://github.com/topcoder-platform/forums/issues/424.

**Comment by sdgun** [comment]
Duplicate of https://github.com/topcoder-platform/forums/issues/424
