### ISSUE TITLE
No Favicon Displayed

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/forums#428]
Our purple favicon that is used on the site disappears when on forums.

<img width="916" alt="Screen Shot 2021-02-22 at 10 19 35 AM" src="https://user-images.githubusercontent.com/1373998/108751840-91fdb700-74f7-11eb-926f-17d75e64ddd7.png">

**Comment by jmgasper** [comment]
Fixed

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/108857498-29a2f880-7611-11eb-8205-b46edac8760a.png)
