### ISSUE TITLE
Copilot sees the Edit on challenges, but when tries to do a change and Save, see an error

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#441]
Steps
Log in as TCConnCopilot to forums
Go to https://vanilla.topcoder-dev.com/groups/mine?filter=challenge
Click on ellipsis on a challenge forum
Click Edit
Do a change
Save

https://user-images.githubusercontent.com/4592712/109147124-a9a09e00-778a-11eb-909d-77b0b302bf89.mp4

**Comment by jmgasper** [comment]
@sdgun - I tweaked some permissions and this should now be fixed.

**Comment by jmgasper** [comment]
I also made the same changes in prod, just FYI.

**Comment by sdgun** [comment]
Verified in Dev and Prod, the Edit option is removed from copilot user now. 

![image](https://user-images.githubusercontent.com/4592712/109261433-c9d16b00-7825-11eb-9ebf-5bfd8889fd9a.png)

**Comment by lakshmiathreya** [comment]
@sdgun this should be moved to current milestone from the future milestone 1.x since its working now right?
