### ISSUE TITLE
Delete Discussion isn't working - 403

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/forums#461]
This forum post was made in error:
https://discussions.topcoder.com/discussion/3659/copilot-onboarding-draft-a-challenge-completion

When we click the 3 dots to delete, We're getting a 403 error.
![Screen Shot 2021-03-10 at 10 41 34 AM](https://user-images.githubusercontent.com/5400156/110655889-75b37880-818d-11eb-8504-d32cf3e59ca6.png)

![Screen Shot 2021-03-10 at 10 42 16 AM](https://user-images.githubusercontent.com/5400156/110655913-7b10c300-818d-11eb-8c6e-7cd2b6e6b557.png)

This is the request URL:
https://discussions.topcoder.com/discussion/delete?discussionid=3659&target=https%3A%2F%2Fdiscussions.topcoder.com%2Fcategories%2Fcopilot-discussions&DeliveryType=VIEW

**Comment by atelomycterus** [comment]
@rootelement We've fixed it - https://github.com/topcoder-platform/forums/issues/458.
