### ISSUE TITLE
Alignment issue in Reply and Quote(Firefox)

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#495]
**Steps**
Log into Forums from Firefox browser
Go inside a discussion which has comments and check the quote and reply in the bottom right hand corner of the comment

They are not aligned properly in Firefox

![image](https://user-images.githubusercontent.com/4592712/112587704-1491d300-8e24-11eb-99cb-92897b5d0235.png)

**Comment by atelomycterus** [comment]
@sdgun Please clear browser cache:

![image](https://user-images.githubusercontent.com/10196632/112591422-63843c00-8e15-11eb-81ed-884fa04a4e76.png)

**Comment by sdgun** [comment]
@atelomycterus My bad, it looks good when cache is cleared.
