### ISSUE TITLE
In Threaded view the page numbers are not displayed 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#498]
**Steps**
Go to a discussion with more than 1 page of comments(ex-https://vanilla.topcoder-dev.com/discussion/3559/perf-2?view=threaded)

Pagination is not there

https://user-images.githubusercontent.com/4592712/112707974-23848e00-8ed5-11eb-9571-dfd3c312b21e.mp4

**Comment by atelomycterus** [comment]
@sdgun  Now Threaded View is default (https://github.com/topcoder-platform/forums/issues/395). Threaded View doesn't  support paging, all comments are displayed on one page - https://github.com/topcoder-platform/forums/issues/256#issuecomment-738862904

Flat View supports paging.

**Comment by sdgun** [comment]
@atelomycterus Thanks, A few issues I found, please let me know if you want me to report them separately

1. For anonymous users, Threaded view supports pagination

![image](https://user-images.githubusercontent.com/4592712/112743152-7b44f700-8fb2-11eb-9a6b-338540eb5e28.png)


2. For anonymous users, the comments on the first page of threaded view do not display the text "Re: <discussion title>..."

https://user-images.githubusercontent.com/4592712/112743205-e2fb4200-8fb2-11eb-9536-8e969b330b4c.mp4

**Comment by atelomycterus** [comment]
@sdgun I've fixed views for anonymous in (https://github.com/topcoder-platform/forums/pull/504,
https://github.com/topcoder-platform/forums-plugins/pull/76). If you find new issues, please report them separately. Thanks!

**Comment by sdgun** [comment]
Verified the pagination and the reference text on comments for anonymous users in Dev. The issues are fixed.

**Comment by sdgun** [comment]
Verified in production.

![image](https://user-images.githubusercontent.com/4592712/113256663-1f96a880-92e7-11eb-878e-190b8f5cf8da.png)
