### ISSUE TITLE
Forums -> Email Communication

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/forums#5]
Forum/email communication, and can you reply to an email?

**Comment by jmgasper** [comment]
I'm not sure this is possible with the open source version.

There was a plugin for this, but it's defunct.  We may be able to revive it, but there are all sorts of security implications to consider.

https://open.vanillaforums.com/addon/replybyemail-plugin

### Paid

There is a paid feature of the `Enterprise` forums that sounds like it supports this:

https://success.vanillaforums.com/kb/articles/24-vanilla-pop-forum-email-interaction

**Comment by rootelement** [comment]
This could be a problem. How hard do you think it'd be to write our own? You need to write an email listener right? That could be too much...

**Comment by jmgasper** [comment]
Yeah, we could probably find something to start with and then modify to our needs, but I'd be nervous about security / spamming via the email address.  I'm not one to use the email reply much - how is that validated by Jive?
