### ISSUE TITLE
Public Forums is selected while the user is in category view

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#512]
**Steps**
Go to https://vanilla.topcoder-dev.com/categories/27e27c60-02d2-4730-b726-d3cf0099788f
User is in a challenge forum but in the left nav, Public forums is selected

![image](https://user-images.githubusercontent.com/4592712/112953053-c3068280-915a-11eb-992c-6a9999929452.png)

**Comment by atelomycterus** [comment]
@sdgun @jmgasper  Duplicated issue. Fixed in https://github.com/topcoder-platform/forums/issues/518.
