### ISSUE TITLE
[Sporadic]The replies are not shown under the relevant comment until the page is refreshed

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#515]
**Steps**
Go to a discussion with 2 comments
Reply to the 1st comment

The reply is displayed last under the 2nd comment
After a refresh it is displayed under 1st comment

https://user-images.githubusercontent.com/4592712/113268039-99815e80-92f4-11eb-877f-85c8f0c2e0b2.mp4

**Comment by jmgasper** [comment]
Similar to https://github.com/topcoder-platform/forums/issues/511
