### ISSUE TITLE
The Quote / Edit / Reply links in the Threads box are uneven

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/forums#517]
I am currently logged in as a regular user and when I commented on the thread post i see the below:

<img width="1317" alt="Screen Shot 2021-04-01 at 10 31 37 AM" src="https://user-images.githubusercontent.com/1373998/113331980-74c9be80-92d5-11eb-8c46-7165715c81b8.png">

**Comment by atelomycterus** [comment]
@hokienick Please clear browser cache. The links should be in blue:
![image](https://user-images.githubusercontent.com/10196632/113332662-24c91700-932a-11eb-9f76-c5448663c8b4.png)

**Comment by atelomycterus** [comment]
@jmgasper You can close it. ☝️ Thanks!
