### ISSUE TITLE
Clicking preview before entering a text shows the "Cannot post an empty message" error message

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#541]
**Steps**
Go to any discussion
Click Preview without entering anything in the comment text field

**Actual behavior**
Shows error message "Cannot post an empty message"

**Expected behavior**
Before we implement this error message fixes, we allowed previewing when no text is entered

https://user-images.githubusercontent.com/4592712/113665147-96a6b500-96ca-11eb-9ad6-79f142c2452a.mp4

**Comment by jmgasper** [comment]
I think this is fine now - no need to allow previewing an empty message.
