### ISSUE TITLE
When expanding other sections, while General section is expanded, the focus is not happening correct

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#551]
**Steps**

- Go to Forums home page(log in or log out view)
- While General section is expanded, click on other sections to expand them

The page scrolls down and does not focus on the relevant section

https://user-images.githubusercontent.com/4592712/113991327-fd190800-986f-11eb-8fd1-e4a1f989ce09.mp4

**Comment by jmgasper** [comment]
@atelomycterus - Can we fix this one before the deploy tomorrow please?

**Comment by atelomycterus** [comment]
@jmgasper sure, I’ll be at home in 1,5 hours and fix it ASAP + home redesign breadcrumbs.

**Comment by atelomycterus** [comment]
@jmgasper Fixed. Please apply https://github.com/topcoder-platform/forums/pull/552. Thanks!

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.

**Comment by sdgun** [comment]
Verified in production.
