### ISSUE TITLE
The description is changed in the challenge forums list

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#580]
**Steps**
Go to https://vanilla.topcoder-dev.com/groups/mine?filter=challenge
Check the latest challenges

The description shows the url and the challenge name within brackets

![image](https://user-images.githubusercontent.com/4592712/115104602-3429a080-9f77-11eb-8125-d5489ea704f5.png)

**Comment by atelomycterus** [comment]
@sdgun Thanks for notice that! Fixed. The group description should be formatted to html.

![image](https://user-images.githubusercontent.com/10196632/115110305-59241080-9f83-11eb-8054-13a4d6b990ac.png)


@jmgasper Please apply PR - https://github.com/topcoder-platform/forums-groups-plugin/pull/81

**Comment by sdgun** [comment]
Verified in Dev.

![image](https://user-images.githubusercontent.com/4592712/115130191-042bdd00-a00b-11eb-9b32-0703aacfbb48.png)
