### ISSUE TITLE
Unable to create a new thread

### ISSUE THREAD

**Issue by ketzjs09** [topcoder-platform/forums#605]
I'm unable to create a new thread in the forums. As of now, I'm noticing this in a private channel, but I noticed the same last week in a challenge that I was copiloting. The challenge was complete, so I assumed maybe the new forum does not allow new threads to be created in completed challenges, but I'm noticing it here as well. 

![forum_blurred](https://user-images.githubusercontent.com/62241220/116211594-9ba6d380-a761-11eb-9381-99e192153502.png)

(Note - the threads has been deliberately cut out from the image (now in blue) for privacy of this private forum)

**Comment by jmgasper** [comment]
@ketzjs09 - Any errors in the JS console? What browser are you using?

**Comment by ketzjs09** [comment]
Using Microsoft Edge (based on Chromium)
Version 90.0.818.49 (Official build) (64-bit)

![console](https://user-images.githubusercontent.com/62241220/116219330-1f17f300-a769-11eb-9e3c-9214cfc43ff7.PNG)

**Comment by ketzjs09** [comment]
Tested it on Chrome, and can see the 'New Discussion' button on it, but not on Edge.

**Comment by atelomycterus** [comment]
@ketzjs09 Please clear browser cache  in Microsoft Edge. I've tested it in Microsoft Edge, no issues. Let me know if the issue exists. 

Testing with Version 90.0.818.49 (Official build) (64-bit):
![image](https://user-images.githubusercontent.com/10196632/116287118-b21c5180-a798-11eb-831b-d28b863bd1bb.png)


![image](https://user-images.githubusercontent.com/10196632/116286794-4f2aba80-a798-11eb-8be3-fea1d4ad6920.png)
