### ISSUE TITLE
The text in the footer in mobile devices is not shown in one line

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#630]
Footer in mobile devices is shown like below:

![image](https://user-images.githubusercontent.com/4592712/120744159-09d87600-c518-11eb-8d92-99260e67bec4.png)

Device: iPhone 6S
OS: 13.7
Browser: Safari

Device: Pixel XL
OS: Android 10
Browser: Chrome

**Comment by atelomycterus** [comment]
@sdgun I missed it. Fixed. Thanks for testing! 

@jmgasper Please apply PR-https://github.com/topcoder-platform/forums-theme/pull/62. Thanks!

### Testing
Please clear browser cache before testing.
![image](https://user-images.githubusercontent.com/10196632/120786524-fc7eb400-c536-11eb-9920-46208e3029ac.png)

**Comment by sdgun** [comment]
Verified in Dev.

**Comment by sdgun** [comment]
Verified in production.

![IMG_6766](https://user-images.githubusercontent.com/4592712/122527034-94e95e00-d038-11eb-8320-db38abf0c0f7.jpg)
