### ISSUE TITLE
Investigate Latex

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#65]
@rootelement  - I heard Latex mentioned in the copilot video.  Do we want to investigate supporting it?  There is an existing plugin, but it's old.  Might be a good starting point though.  The plugin isn't very complex:

https://open.vanillaforums.com/addon/latex-plugin

**Comment by rootelement** [comment]
Not for v1 release. But it on the backlog. It was just Sergey asking. Not sure how important this is.
