### ISSUE TITLE
Universal nav integration updates

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#689]
### Issue 1

I've integrated Tool Navigation and the Footer Navigation with a hard-coded user in the forum theme.
We should add and fix several files in the forums repo(https://github.com/topcoder-platform/forums) to implement all requiremets.
'We have to ensure that it displays properly for: Anonymous (not logged in) user + Logged in user'
The forums theme uses Smarty templates. Smarty is a web template system written in PHP, facilitating the separation of presentation (HTML/CSS) from application logic. Vanilla Forums uses Topcoder JWT token to authenticate users and we need to use the data in smarty templates from session. Unfortunately, we have access to Vanilla User only, not Topcoder User in smart templates. We need to write some logic and commit several files in the forums repo(https://github.com/topcoder-platform/forums) to implement this requirements.

### Issue 2
We need to update config files in the forums repo to support both envs (PROD/DEV) and make URLs to be configurable for the forum-theme.
In the submission section: 'You must submit a patch file against commit hash 2500e65 of the "dev" branch of the forums-theme Github repo'. What commit hash of the forums repo(https://github.com/topcoder-platform/forums) should be used?
Please let me know if there are no changes in the scope of the challenge.

**Comment by atelomycterus** [comment]
@jmgasper The question about user fields. Universal Nav displays user initials at the top of the page. JWT token doesn't contain user initials. I've also looked at a member payload and there are no user initails.
![image](https://user-images.githubusercontent.com/10196632/205922126-1352b5f3-03e0-4226-af7b-861aa937b474.png)

In  the challenge  the tc-website (https://github.com/topcoder-platform/tc-website/commit/e51ce0819226beaa3e6a862ef08bda033d08cedd)  is mentioned for reference. In this commit you can see that user initials are s calculated as  the first two letter from user handle. This is not correct and perhaps this is by mistake. Please let me know if you are ok with that.

**Comment by jmgasper** [comment]
I think using the first two from the user's handle is fine here, thanks.

**Comment by atelomycterus** [comment]
@jmgasper Please apply PRS:
- https://github.com/topcoder-platform/forums-plugins/pull/116
- https://github.com/topcoder-platform/forums-theme/pull/69
- https://github.com/topcoder-platform/forums/pull/690

Thanks!

### Configuration
1. You can configure `UniversalNavUrl` in forums\config\vanilla\config.php. The current configuration:
```
$Configuration['Theme']['UniversalNavUrl'] = getenv('VANILLA_ENV') === 'prod'? '//uni-nav.topcoder.com/v1/tc-universal-nav.js':'//uni-nav.topcoder-dev.com/v1/tc-universal-nav.js';
```
2. User Id Claim, Photo Url Claim  also are availble in congi.php and they are can be configured in Topcoder Plugin  as User name claim.  The current configuration:
```
$Configuration['Plugins']['Topcoder']['SSO']['TopcoderHS256']['UserIDClaim'] = getenv('VANILLA_ENV') == 'prod'? 'https://topcoder.com/userId' : 'https://topcoder-dev.com/userId';
$Configuration['Plugins']['Topcoder']['SSO']['TopcoderRS256']['UserIDClaim'] = getenv('VANILLA_ENV') == 'prod'? 'https://topcoder.com/userId' : 'https://topcoder-dev.com/userId';
$Configuration['Plugins']['Topcoder']['SSO']['TopcoderHS256']['PhotoUrlClaim'] = getenv('VANILLA_ENV') == 'prod'? 'picture' : 'picture';
$Configuration['Plugins']['Topcoder']['SSO']['TopcoderRS256']['PhotoUrlClaim'] = getenv('VANILLA_ENV') == 'prod'? 'picture' : 'picture';
```
 
### Testing
![image](https://user-images.githubusercontent.com/10196632/206150484-fb7b9662-0e30-46ef-bca9-d6fecbbabdee.png)

Please let me know if you have any questuions.

**Comment by jmgasper** [comment]
@atelomycterus - All looks good, thanks!
