### ISSUE TITLE
There is some space under the Footer if the screen content is less.

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#691]
REF: https://topcoder.atlassian.net/browse/PROD-3393

This is related to the new universal nav changes.

Forums: The space under the Footer is always there

![image-20221214-073943](https://user-images.githubusercontent.com/21790/207728334-ff02670f-0d4c-4f74-985f-458bb1fd96d4.png)

**Comment by atelomycterus** [comment]
@jmgasper Fixed. Please apply PR https://github.com/topcoder-platform/forums-theme/pull/70. Thanks!
