### ISSUE TITLE
Allow for colouring handles of a specific group

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#693]
@atelomycterus - We have a client request to be able to colour handles of users of a specific Vanilla group.  This will be used for a specific set of client admins that have some restricted admin permissions on a private group.

We'd like to be able to colour their handles purple (`#652385`), if they are members of a chosen group.  We can hard-code the group name for now.

**Comment by atelomycterus** [comment]
@jmgasper  Please correct me if I am wrong. The challenge named 'XXX' will be created for a client. 
The name of the group should be configured in the config file.
What role should the members of the challenge group have in order to colour their handles purple in Vanilla?
There are many different roles in the challenge ("Approver", "Team Captain", "Client Manager", and etc.) 
I used https://api.topcoder.com/v5/resource-roles to get this list of roles.

**Comment by jmgasper** [comment]
> @jmgasper Please correct me if I am wrong. The challenge named 'XXX' will be created for a client.
> The name of the group should be configured in the config file.
> What role should the members of the challenge group have in order to colour their handles purple in Vanilla?
> There are many different roles in the challenge ("Approver", "Team Captain", "Client Manager", and etc.)
> I used https://api.topcoder.com/v5/resource-roles to get this list of roles.

1. Sorry, this will be a role, not a group, so it'll be tied to a specific role.  My bad for a confusing term.  
2. I created role `ColorTest` in dev for us to test with
3. In prod, the role will be `MIT_6.S099 Admin`

The colour can apply across the entire forums - it doesn't have to be restricted to particular categories or groups.

**Comment by atelomycterus** [comment]
@jmgasper Thanks for the clarification. Keep you updated on it.

**Comment by atelomycterus** [comment]
@jmgasper Please apply the PR:
https://github.com/topcoder-platform/forums/pull/694
https://github.com/topcoder-platform/forums-plugins/pull/119

## Configuration
Please condfigure a role in config.php:
$Configuration['ColorizedRole']='ColorTest';

## Test
![image](https://user-images.githubusercontent.com/10196632/212368406-42793f35-502b-4e3a-bbc7-be724ce10c5f.png)
![image](https://user-images.githubusercontent.com/10196632/212368850-a905950a-fb2d-42ec-bcfb-0bb13fff5701.png)
