### ISSUE TITLE
In All discussion page, the threads are listed, but the challenge name is not shown for the listed threads

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#76]
Steps
Go to the forum of a normal user(ex user- TopConnCustomer group - https://vanilla.topcoder-dev.com/group/128)
Click on the 'All Discussions' link below the threads

Actual result
It is loading a list of threads, the challenge name is not shown for the listed threads so user doesn't know which thread belong to which challenge 

Expected result
Better to have the challenge name or list the threads by challenge

![image](https://user-images.githubusercontent.com/4592712/97541156-b1258580-19ea-11eb-83d6-d1870cd6f8cd.png)

**Comment by jmgasper** [comment]
Gonna mark this as a duplicate, since we're going to remove this link / page.
