### ISSUE TITLE
The comment added/edited time is not the user's current time

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#78]
**Steps**
Go to the forum of a normal user(ex user- TopConnCustomer group - https://vanilla.topcoder-dev.com/group/128)
Add a comment or edit a comment in any thread and check the time

**Actual result**
The time stamp shows a past time

**Expected result**
Should show the comment added/edited time

![image](https://user-images.githubusercontent.com/4592712/97543953-f2b82f80-19ee-11eb-91ef-a1340467d2de.png)

**Comment by jmgasper** [comment]
We don't have a way of pulling the user's timezone from the Topcoder services.  I'm going to mark this for future.
