### ISSUE TITLE
The forum link in the challenge is throwing 502 error

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/forums#98]
**Steps**
Log in and go to challenge https://www.topcoder-dev.com/challenges/3d88d45b-6b1c-4da0-a02d-7f73f7642bd2
Click Challenge forum link

**Actual result**
Throws 502 error

**Expected result**
Should open the vanilla forum of the challenge

![image](https://user-images.githubusercontent.com/4592712/97946361-3d032d00-1db0-11eb-9e5e-c691e8ad4063.png)

**Comment by jmgasper** [comment]
@rootelement - Can I push on this with the community app folks?

**Comment by rootelement** [comment]
It looks like the new forum code is deployed in QA only. It works here:
https://qa-community-app.topcoder-dev.com/challenges/3d88d45b-6b1c-4da0-a02d-7f73f7642bd2

**Comment by sdgun** [comment]
@jmgasper @rootelement This is not working in QA today

**Comment by rootelement** [comment]
@sdgun what's not working. The link I posted above works. Are you saying you created a challenge and it didn't make a forum? Or it did but the community app link isn't taking you to the vanilla instance? What are the steps?

**Comment by sdgun** [comment]
@rootelement It was broken yesterday and luizrrodrigues fixed it https://topcoder.slack.com/archives/CDS7DUUR0/p1604580408271800?thread_ts=1604554177.255900&cid=CDS7DUUR0
